### ISSUE TITLE
Where is the firmware of this dsmr splitter? the directory is empty

### ISSUE THREAD

**Issue by alcomys** [basilfx/DSMR-Splitter#6]
Hello,

Can you help me where to find the firmware for the controller of this dsmr splitter?
I downloaded the complete master but the firmware directory is empty 

Thank you.

**Comment by basilfx** [comment]
See the README.md of the firmware folder, where it states that the source lives in a different repository.

**Comment by alcomys** [comment]
Hi Basilfx,

The README.md in my downloaded Master did not contain any of the links to another repository. 
But when downloaded the Master with an other link it contain the link. 

So you can close this. 

Thank you for the help.
